version: '3.7'
x-labels: &labels
    traefik.backend.loadbalancer.swarm: 'true'
    traefik.backend.loadbalancer.method: 'drr'
    traefik.enable: 'true'

services:
    nginx:
        networks:
            - 'default'
            - 'traefik'
        deploy:
            labels:
                <<: *labels
                traefik.backend: 'sandbox.symfony-cqrs'
                traefik.port: '80'
                traefik.frontend.rule: 'Host:${PROJECT_HOST:?}'
                # sandbox / sandbox
                traefik.frontend.auth.basic.users: 'sandbox:$$apr1$$Ya55vtVw$$6lPtLTGToO3E6wz.NCMOX/'

networks:
    traefik:
        external: true
        name: 'traefik'
