version: '3.7'
services:
    nginx:
        networks:
            - 'default'
            - 'traefik'
        labels:
            traefik.enable: 'true'
            traefik.http.services.symfony.loadbalancer.server.port: '80'
            traefik.http.routers.symfony.rule: 'Host(`local.symfony`)'
            traefik.http.routers.symfony.entrypoints: 'web-secure'
            traefik.http.routers.symfony.tls: 'true'

    traefik:
        labels:
            traefik.enable: 'true'
            traefik.http.services.traefik.loadbalancer.server.port: '8080'
            traefik.http.routers.traefik.rule: 'Host(`local.traefik`)'
            traefik.http.routers.traefik.service: 'api@internal'
            traefik.http.routers.traefik.entrypoints: 'web-secure'
            traefik.http.routers.traefik.tls: 'true'

    whoami:
        networks:
            - 'default'
            - 'traefik'
        labels:
            traefik.enable: 'true'
            traefik.http.services.whoami.loadbalancer.server.port: '80'
            traefik.http.routers.whoami.rule: 'Host(`local.whoami`)'
            traefik.http.routers.whoami.entrypoints: 'web-secure'
            traefik.http.routers.whoami.tls: 'true'
