version: '3.7'
services:
    traefik:
        image: 'traefik:1.7'
        container_name: 'traefik'
        networks:
            - 'default'
            - 'traefik'
        volumes:
            -
                type: 'bind'
                source: '/var/run/docker.sock'
                target: '/var/run/docker.sock'
            -
                type: 'bind'
                source: './build/traefik/tls/acme.json'
                target: '/acme.json'
            -
                type: 'bind'
                source: './build/traefik/config.toml'
                target: '/etc/traefik/traefik.toml'
            -
                type: 'bind'
                source: './build/traefik/configs'
                target: '/etc/traefik/configs'
        ports:
            -
                target: 80
                published: 80
                mode: 'host'
            -
                target: 443
                published: 443
                mode: 'host'
        env_file:
            - './traefik.env'
        command: '--debug --logLevel="DEBUG"'

    whoami:
        image: 'containous/whoami'
        container_name: 'whoami'

networks:
    traefik:
        name: 'traefik'
