version: '3.7'
services:
    traefik:
        image: 'traefik:2.1'
        container_name: 'traefik'
        networks:
            - 'default'
            - 'traefik'
        volumes:
            -
                type: 'bind'
                source: '/var/run/docker.sock'
                target: '/var/run/docker.sock'
            -
                type: 'bind'
                source: './build/traefik/config_local.yaml'
                target: '/etc/traefik/traefik.yaml'
                read_only: true
            -
                type: 'bind'
                source: './env/local/certs'
                target: '/certs'
                read_only: true
        ports:
            -
                target: 80
                published: 80
                mode: 'host'
            -
                target: 443
                published: 443
                mode: 'host'
        env_file:
            - './traefik.env'

    whoami:
        image: 'containous/whoami'
        container_name: 'whoami'

networks:
    traefik:
        name: 'traefik'
